# --- Ansible runtime ---
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa_ecs.pem
ansible_python_interpreter: /usr/bin/python3

# --- Environment ---
env: dev          # dev | qa | prod
timezone: UTC