# Variables espec√≠ficas
app_name: "mi-servicio-java"
app_port: 8080
app_endpoint: "/healthCheck"
app_jar_name: "app-basic-java-0.0.1-SNAPSHOT.jar"
java_version: 21

ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa_ecs.pem
#ansible_ssh_private_key_file: "{{ playbook_dir }}/../files/keys/id_rsa_ecs.pem"
ansible_python_interpreter: /usr/bin/python3