# --- RDS PostgreSQL ---
db_host: 10.1.86.174
db_port: 5432
db_name: postgres
db_user: root
db_password: P@ssw0rdSecure123!

#export PGPASSWORD=********

# --- Restore ---
db_dump_file: cliente-dump.sql

ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa_ecs.pem
#ansible_ssh_private_key_file: "{{ playbook_dir }}/../files/keys/id_rsa_ecs.pem"
ansible_python_interpreter: /usr/bin/python3